LoggingSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('home.urls', namespace='home')),
	url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^logs/', include('logs.urls', namespace='logs')),
   # url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
]

home/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as views_for_user

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', views.index, name='index'),
    
    url(r'^login/$', views_for_user.login, {'template_name': 'profile_login.html'}, name='account_login'),
    url(r'^logout/$', views_for_user.logout, {'template_name': 'profile_logged_out.html'}, name='account_logout'),
    url(r'^logs/easteregg/$', views.signup),
    url(r'^update_profile/$', views.update_profile, name='account_update'),
    url(r'^profile/$', views.profile, name='account_info'),
    url(r'^about_us/$', views.about_us, name='about_us'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_log/$', views.new_log, name='new_log'),
    url(r'^list_logs/$', views.list_logs, name='list_logs'),
    url(r'^(?P<log_id>[0-9]+)/$', views.single_log),
    url(r'^(?P<log_id>[0-9]+)/delete/$', views.delete),
    url(r'^(?P<log_id>[0-9]+)/modify/$', views.modify),
    url(r'^search/$', views.search),
    url(r'^backup/$', views.backup, name='backup_logs'),
]

templates/deleted.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h3>{% trans 'Log successfully deleted!' %}</h3>
<div class="data">
<a href="/logs">{% trans 'LIST LOGS' %}</a>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

<h3>{% trans 'Welcome' %},
{% if request.user.get_full_name %}
{{ request.user.get_full_name }}!
{% else %}
{{ request.user }}!
{% endif %}
</h3>

<h1>{% trans 'Statistics' %}</h1>
<div class="info" style="border-top: dashed 1px gray;">
    <label>{% trans 'Total Income:' %}</label>
    <label class="value">{{ total_price }}</label>
</div>
<div class="info">
    <label>{% trans 'Total Logs:' %}</label>
    <label class="value">{{ total_data }}</label>
</div>
<div class="info">
    <label>{% trans 'Date Joined:' %}</label>
    <label class="value">{{ date_joined }}</label>
</div>
<div class="info">
    <label>{% trans 'Days Registered:' %}</label>
    <label class="value">{{ days_registered }}</label>
</div>

<div class="columns">
<a href="{% url 'logs:backup_logs' %}">{% trans 'DOWNLOAD DATA' %}</a>
<a href="{% url 'home:about_us' %}">{% trans 'ABOUT US & CONTACT' %}</a>
</div>
{% endblock %}

templates/log_error_not_found.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h3>{% trans 'Error, Requested log not found!' %}</h3>
<div class="data">
<a href="{% url 'logs:list_logs' %}">{% trans 'LIST LOGS' %}</a>
</div>
{% endblock %}

templates/log_error_owner.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h3>{% trans 'Error, You are not owner of requested log!' %}</h3>
<div class="data">
<a href="{% url 'logs:list_logs' %}">{% trans 'LIST LOGS' %}</a>
</div>
{% endblock %}

templates/log_new.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

        <h1 class="header">{% trans 'New Log:' %}</h1>
        <form method="post" class="">
    {% csrf_token %}
    {% for field in form %}
        <label>{{ field.label_tag }}</label>
        {{ field }}
        
    {% if field.errors %}
        {{ field.errors }}
        {% endif %}
    {% endfor %}
        <button value="Submit">{% trans 'SUBMIT' %}</button>

</form>
{% endblock %}

templates/log_single.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h1 class="header">{{ data.name }}</h1>

<div class="info" style="border-top: dashed 1px gray;">
    <label>{% trans 'Date: ' %}</label>
    <label class="value">{{ data.timestamp }}</label>
</div>
<div class="info">
    <label>{% trans 'Phone: ' %}</label>
    <label class="value">{{ data.contact }}</label>
</div>
<div class="info">
    <label>{% trans 'Manufacturer: ' %}</label>
    <label class="value">{{ data.manufacturer }}</label>
</div>
<div class="info">
    <label>{% trans 'Model: ' %}</label>
    <label class="value">{{ data.model }}</label>
</div>
<div class="info">
    <label>{% trans 'Price: ' %}</label>
    <label class="value">{{ data.price }} мкд</label>
</div>
<div class="info">
    <label>{% trans 'Description: ' %}</label>
    <label class="value">{{ data.description }}</label>
</div>


<div class="columns">
<a href="" onclick="window.print();">{% trans 'PRINT' %}</a>
<a href="/logs/{{ data.id }}/modify">{% trans 'MODIFY' %}</a>
<a href="/logs/{{ data.id }}/delete">{% trans 'DELETE' %}</a>
</div>

{% endblock %}

templates/logged_out.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h3>{% trans 'You successfully signed out.' %}<br></h3>
<div class="data">
<a href="{% url 'home:account_login' %}">{% trans 'LOG IN AGAIN' %}</a>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h2>{% trans 'Login' %}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% trans 'Login' %}</button>
</form>
{% endblock %}

templates/profile_logged_out.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h3>{% trans 'You successfully signed out.' %}<br></h3>
<div class="data">
<a href="{% url 'home:account_login' %}">{% trans 'LOG IN AGAIN' %}</a>
</div>
{% endblock %}

templates/profile_signup.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <h2>{% trans 'Registration:' %}</h2>
  <center><form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p style="width: 50%;">
        {{ field.label_tag }}<br>
        <p >{{ field }}</p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">{% trans 'REGISTER' %}</button>
  </form></center>
{% endblock %}

templates/profile_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">{% trans 'SAVE CHANGES' %}</button>
</form>
{% endblock %}

templates/profile_wrong_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h3>{% trans 'Error, wrong password!' %}</h3>
<div class="data">
<a href="{% url 'logs:list_logs' %}">{% trans 'LIST LOGS' %}</a>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <h2>{% trans 'Registration:' %}</h2>
  <center><form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p style="width: 50%;">
        {{ field.label_tag }}<br>
        <p >{{ field }}</p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">{% trans 'REGISTER' %}</button>
  </form></center>
{% endblock %}

templates/submited.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h3>{% trans 'Log successfully submited!' %}</h3>
<div class="data">
<a href="/logs">{% trans 'LIST LOGS' %}</a>
</div>
{% endblock %}